version: '3.5'

services:

   laravel:
     build:
       context: .
       args:
         user: '1000'
         uid: '1000'
     container_name: laravel_osid
     tty: true
     volumes:
       - ./:/var/www/html
     networks:
       - laravel_net

   nginx:
     image: nginx:stable-alpine
     container_name: nginx_osid
     tty: true
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - ./:/var/www/html
       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
     depends_on:
       - db
       - laravel
     networks:
       - laravel_net

   db:
     build: ./docker/mysql/.
     container_name: mysql_osid
     environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     networks:
       - laravel_net
     ports:
       - "3306:3306"
     volumes:
       - ./docker/mysql/files:/var/lib/mysql

networks:
  laravel_net: